### PR TITLE
Long term support

### PR DESCRIPTION
**Pull request by alexander-sung**
This pull request aims to prepare repository DFKI-NI/mobipick_tables_demo for "long-term support", beyond the original scope of the castle demo. It includes structure and changes made in the https://github.com/aiplan4eu/mobipick-use-case repository, which therefore should become obsolete and be deleted. The following open points remain:

- The uplexmo example currently does not work due to an issue in the SequentialSimulator implementation. @sebastianstock identified it and already created an issue: https://github.com/aiplan4eu/unified-planning/issues/302. Sebastian has a workaround but we agreed for it not to be part of this pull request.
- Access to the dependency https://github.com/aiplan4eu/unified-planning-bridge needs to be granted. We might need to discuss the feasibility on this.
- Update README.md some more to reflect the state beyond the castle demo.
- The repository shall get a more suitable name.

### CODE REVIEW

**Comment by sebastianstock** [comment]
> * The uplexmo example currently does not work due to an issue in the SequentialSimulator implementation. @sebastianstock identified it and already created an issue: [SequentialSimulator cannot be used with problems that have QualityMetrics aiplan4eu/unified-planning#302](https://github.com/aiplan4eu/unified-planning/issues/302). Sebastian has a workaround but we agreed for it not to be part of this pull request.

I have added the temporary workaround in the branch [temporary_simulator_fix](https://github.com/aiplan4eu/unified-planning-bridge/tree/temporary_simulator_fix) of the unified-planning-bridge repository.

**Comment by sebastianstock** [comment]
> * Access to the dependency https://github.com/aiplan4eu/unified-planning-bridge needs to be granted. We might need to discuss the feasibility on this.

Good point. I would not have a problem to make it public, although it is still in a early stage. But we need to discuss that with the others.
For now,  I have given Martin, Amos and Marc access to the repository.

**Comment by mintar** [comment]
I tried this PR today. Installation went well, but when trying to run the Gazebo demo, I got a couple of problems:

    AssertionError: unified_planning needs a pyparsing version >= 3. Current version detected: 2.4.6, please update it.

I fixed this by running:
    
    pip install pyparsing --upgrade

Then I tried running it again, but now it's missing up_bridge:    

    $ rosrun tables_demo_planning tables_demo_node.py
    Traceback (most recent call last):
      File "/home/mguenther/ros/noetic/mobipick/devel/lib/tables_demo_planning/tables_demo_node.py", line 15, in <module>
        exec(compile(fh.read(), python_script, 'exec'), context)
      File "/home/mguenther/ros/noetic/mobipick/src/mobipick_tables_demo/tables_demo_planning/nodes/tables_demo_node.py", line 60, in <module>
        from tables_demo_planning.tables_demo import TablesDemoDomain, TablesDemoEnv, TablesDemoRobot
      File "/home/mguenther/ros/noetic/mobipick/src/mobipick_tables_demo/tables_demo_planning/src/tables_demo_planning/tables_demo.py", line 46, in <module>
        from tables_demo_planning.demo_domain import Domain
      File "/home/mguenther/ros/noetic/mobipick/src/mobipick_tables_demo/tables_demo_planning/src/tables_demo_planning/demo_domain.py", line 48, in <module>
        from up_bridge.bridge import Bridge
    ModuleNotFoundError: No module named 'up_bridge'

The `unified-planning-bridge` repo is checked out, but it doesn't have a `setup.py`, and there are no instructions in the `install-deps.sh` script to build it.

**Comment by sebastianstock** [comment]
https://github.com/aiplan4eu/unified-planning-bridge is now public.

**Comment by sebastianstock** [comment]
> I tried this PR today. Installation went well, but when trying to run the Gazebo demo, I got a couple of problems:
> 
> ```
> AssertionError: unified_planning needs a pyparsing version >= 3. Current version detected: 2.4.6, please update it.
> ```
> 
> I fixed this by running:
> 
> ```
> pip install pyparsing --upgrade
> ```
> 
> Then I tried running it again, but now it's missing up_bridge:
> 
> ```
> $ rosrun tables_demo_planning tables_demo_node.py
> Traceback (most recent call last):
>   File "/home/mguenther/ros/noetic/mobipick/devel/lib/tables_demo_planning/tables_demo_node.py", line 15, in <module>
>     exec(compile(fh.read(), python_script, 'exec'), context)
>   File "/home/mguenther/ros/noetic/mobipick/src/mobipick_tables_demo/tables_demo_planning/nodes/tables_demo_node.py", line 60, in <module>
>     from tables_demo_planning.tables_demo import TablesDemoDomain, TablesDemoEnv, TablesDemoRobot
>   File "/home/mguenther/ros/noetic/mobipick/src/mobipick_tables_demo/tables_demo_planning/src/tables_demo_planning/tables_demo.py", line 46, in <module>
>     from tables_demo_planning.demo_domain import Domain
>   File "/home/mguenther/ros/noetic/mobipick/src/mobipick_tables_demo/tables_demo_planning/src/tables_demo_planning/demo_domain.py", line 48, in <module>
>     from up_bridge.bridge import Bridge
> ModuleNotFoundError: No module named 'up_bridge'
> ```
> 
> The `unified-planning-bridge` repo is checked out, but it doesn't have a `setup.py`, and there are no instructions in the `install-deps.sh` script to build it.

I have just added the installation of `unified-planning-bridge` to `install-deps.sh`.
It uses its pyproject.toml.
I am only not sure if it needs a more recent pip version then you have installed. I currently have pip 22.3.1. Please check if it now works for you.

**Comment by alexander-sung** [comment]
Sorry for the problems, @mintar, and thanks for reacting, @sebastianstock. I wanted to repond earlier to this but was drown in meetings recently.

Yes, the installation command was missing but the config is a `pyproject.toml` instead of a `setup.py`. Not sure if you saw the format before. I overlooked this file first as well. With regard to the pyparsing version, I encountered the same problem on CI/CD but this needs a proper solution in the UP repository, I'd say. Hopefully it works for you now.

**Comment by mintar** [comment]
>  I am only not sure if it needs a more recent pip version then you have installed. I currently have pip 22.3.1.

That must be it, then. I have the default pip that comes with Ubuntu 20.04 (pip version 20.0.2). This throws the following error:

```text
$ pip install -e unified-planning-bridge/
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/mguenther/ros/noetic/mobipick/src/unified-planning-bridge
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

Can you add a setup.py to the unified-planning-bridge repo, so that it also works with pip 20.0.2? Otherwise, we would have to add instructions to update pip to `install-deps.sh`, and then we have to add instructions to create a virtualenv beforehand, and that quickly becomes complicated.

**Comment by sebastianstock** [comment]
> Can you add a setup.py to the unified-planning-bridge repo, so that it also works with pip 20.0.2? Otherwise, we would have to add instructions to update pip to `install-deps.sh`, and then we have to add instructions to create a virtualenv beforehand, and that quickly becomes complicated.

I have added a dummy setup.py to the bridge.  Tested it successfully in a virtualenv with the old pip version.

**Comment by sebastianstock** [comment]
> > * The uplexmo example currently does not work due to an issue in the SequentialSimulator implementation. @sebastianstock identified it and already created an issue: [SequentialSimulator cannot be used with problems that have QualityMetrics aiplan4eu/unified-planning#302](https://github.com/aiplan4eu/unified-planning/issues/302). Sebastian has a workaround but we agreed for it not to be part of this pull request.
> 
> I have added the temporary workaround in the branch [temporary_simulator_fix](https://github.com/aiplan4eu/unified-planning-bridge/tree/temporary_simulator_fix) of the unified-planning-bridge repository.

This issue is now resolved in unified-planning. In 13761c4 I have therefore updated the installed version of unified-planning to the most recent development version.

**Comment by mintar** [comment]
Is there a reason why we need the `-e` parameter in `pip install -e unified-planning-bridge/`?

That produces the following error (without a virtualenv):

```text
$ pip install -e unified-planning-bridge/
Obtaining file:///home/mguenther/ros/noetic/mobipick/src/unified-planning-bridge
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: unified-planning in /home/mguenther/.local/lib/python3.8/site-packages (from up-bridge==0.0.0) (0.5.0.34.dev1)
Requirement already satisfied: pyparsing in /home/mguenther/.local/lib/python3.8/site-packages (from unified-planning->up-bridge==0.0.0) (3.0.9)
Requirement already satisfied: networkx in /usr/lib/python3/dist-packages (from unified-planning->up-bridge==0.0.0) (2.4)
Installing collected packages: up-bridge
  Running setup.py develop for up-bridge
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mguenther/ros/noetic/mobipick/src/unified-planning-bridge/setup.py'"'"'; __file__='"'"'/home/mguenther/ros/noetic/mobipick/src/unified-planning-bridge/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
         cwd: /home/mguenther/ros/noetic/mobipick/src/unified-planning-bridge/
    Complete output (44 lines):
    running develop
    /tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    WARNING: The user site-packages directory is disabled.
    Checking .pth file support in /home/mguenther/.local/lib/python3.8/site-packages
    /usr/bin/python3 -E -c pass
    TEST PASSED: /home/mguenther/.local/lib/python3.8/site-packages appears to support .pth files
    /tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/mguenther/ros/noetic/mobipick/src/unified-planning-bridge/setup.py", line 5, in <module>
        setuptools.setup()
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.ensure_finalized()
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/setuptools/command/develop.py", line 52, in finalize_options
        easy_install.finalize_options(self)
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 311, in finalize_options
        self.local_index = Environment(self.shadow_path + sys.path)
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1044, in __init__
        self.scan(search_path)
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in scan
        self.add(dist)
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1096, in add
        dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2631, in hashcmp
        self.parsed_version,
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2678, in parsed_version
        self._parsed_version = parse_version(self.version)
      File "/tmp/pip-build-env-jhn4c_lr/overlay/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
        raise InvalidVersion(f"Invalid version: '{version}'")
    pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '2.20.2ubuntu2'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mguenther/ros/noetic/mobipick/src/unified-planning-bridge/setup.py'"'"'; __file__='"'"'/home/mguenther/ros/noetic/mobipick/src/unified-planning-bridge/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
```

However, if I just do the following: `pip install unified-planning-bridge/` (no `-e`), it works, **even without a unified-planning-bridge/setup.py**.

**Comment by alexander-sung** [comment]
I pushed the fix for #8 into this pull request's branch by accident and force-pushed to undo it.

**Comment by sebastianstock** [comment]
> Is there a reason why we need the `-e` parameter in `pip install -e unified-planning-bridge/`?

It is not critical to have it. By making the bridge's installation editable it just makes it a little easier such that you don't need to re-install it after you do some local changes in the bridge.
Therefore, I just removed it with commit [ad5a200](https://github.com/DFKI-NI/mobipick_tables_demo/pull/10/commits/ad5a200e8907066a66a91bd6b71e677d00f53032).

**Comment by mintar** [comment]
I had to fix some pre-commit errors (13761c4b68794a8343c5046aaefdd2e0b3b8511a). @sebastianstock, you should probably install pre-commit as described in the README.

**Comment by sebastianstock** [comment]
> I had to fix some pre-commit errors ([13761c4](https://github.com/DFKI-NI/mobipick_tables_demo/commit/13761c4b68794a8343c5046aaefdd2e0b3b8511a)). @sebastianstock, you should probably install pre-commit as described in the README.

Sorry! I thought I had that already. Thanks for the notification. @mintar

**Comment by mintar** [comment]
I've cleaned up the Git history a bit and force-pushed the branch (no changes except cleaner git history). Ready to merge!

**Review by mintar — APPROVED** [review]

**Comment by mintar** [comment]
I've opened issues for the remaining open points:

- Update README.md some more to reflect the state beyond the castle demo (#13)
- The repository shall get a more suitable name (#14)

**Pull request merged**
