### PR TITLE
Refactor pick_n_place_demo

### PR DESCRIPTION
**Pull request by sebastianstock**
As discussed in #17 I refactored pick_n_place_demo_node to move the main functionality into src.

### CODE REVIEW

**Comment by mintar** [comment]
The pre-commit tests are failing.

* Remove the executable flag from `src/tables_demo_planning/pick_n_place_demo.py`
* Reformat Python code using `black` (pre-commit will do that automatically when you run it).

Please install pre-commit as detailed in the README and run `pre-commit run -a` to see the errors.

I should really migrate the existing Gitlab CI to GitHub actions...

**Comment by mintar** [comment]
You could also remove the hashbang line (`#!/usr/bin/env python3`) from `src/tables_demo_planning/pick_n_place_demo.py`, because it doesn't have a `main` and is not executable.

**Comment by alexander-sung** [comment]
Very nice. It's working fine for me, just please consider Martin's suggestions. I would also add some more empty lines due to conventions but the pre-commit will handle it automatically. Especially, I liked that you're using a top level `run_demo()` function where I would use a subclass and class method. Good to see that there are no hidden class interfaces.

I tested both demos, using your `temporary_simulator_fix` branch for the uplexmo version as discussed before.

**Comment by sebastianstock** [comment]
Thanks for pointing to the pre-commit error. I seemed I had  problem in my installation that prevented pre-commit from running properly.
I also update the pre-commit config due to the move of flake8 form gitlab to github.

**Pull request merged**
